name: build
on:
  pull_request:
  push:
  schedule:
    - cron: 35 8 3 * *
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: macos-latest, stack: lts-5.18 }
          - { os: macos-latest, stack: lts-17.5 }
            # cabal-1.16 is the earliest available in the ppa:hvr/ghc for ubuntu-16.04
          - { os: ubuntu-20.04, ghc: 7.4.2, cabal: "2.4", overrides: "before_prepare() { sed -i.bak /utimensat/d configure.ac; }" }
          - { os: ubuntu-20.04, ghc: 7.4.2, cabal: "2.4" }
          - { os: ubuntu-18.04, ghc: 7.6.3, cabal: "2.4" }
          - { os: ubuntu-18.04, ghc: 7.8.4, cabal: "2.4" }
          - { os: ubuntu-latest, ghc: 7.10.3, cabal: "2.4", overrides: 'before_prepare() { [ -f ~/.cabal/config ] || cabal user-config init; sed -i "s/-- ghc-options:.*/ghc-options: -optl-no-pie/" ~/.cabal/config; }' }
          - { os: ubuntu-latest, ghc: 8.0.2, cabal: "2.4" }
          - { os: ubuntu-latest, ghc: 9.0.1, cabal: 3.4.0.0 }
          - { os: ubuntu-latest, ghc: latest, cabal: latest }
          - { os: windows-latest, stack: lts-4.2, stack-extra-deps: "time-1.5.0.1, Win32-2.3.0.1", overrides: "before_prepare() { sed -i.bak -e /CreateSymbolicLinkW/d -e /GetFinalPathNameByHandleW/d configure.ac; }" }
          - { os: windows-latest, stack: lts-5.18 } # time-1.5.0.1, Win32-2.3.1.0
          - { os: windows-latest, stack: lts-7.24, stack-extra-deps: "time-1.6.0.1, Win32-2.4.0.0" }
          - { os: windows-latest, stack: lts-9.21, stack-extra-deps: "time-1.6.0.1, Win32-2.8.0.0" }
          - { os: windows-latest, stack: lts-17.5 } # time-1.9.3, Win32-2.6.1.0
          - { os: windows-latest, stack: lts-18.26, stack-extra-deps: "time-1.12.1, Win32-2.13.2.0" }
    runs-on: ${{ matrix.os }}
    env:
      TESTSCRIPT_OVERRIDES: ${{ matrix.overrides }}
      STACK_EXTRA_DEPS: ${{ matrix.stack-extra-deps }}
      STACK_RESOLVER: ${{ matrix.stack }}
    steps:
      - if: startsWith(matrix.os, 'macos-')
        run: brew install automake
      - if: startsWith(matrix.os, 'ubuntu-')
        # required since https://github.com/actions/virtual-environments/pull/3268
        run: |
          sudo add-apt-repository ppa:hvr/ghc
          sudo apt-get update
      - if: startsWith(matrix.os, 'windows-')
        run: |
          echo STACK_FLAGS=--skip-msys >> $GITHUB_ENV
          echo 'C:\msys64\usr\bin' >> $GITHUB_PATH
      - if: startsWith(matrix.os, 'windows-')
        run: |
          pacman -S --needed --noconfirm autoconf automake
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: ${{ matrix.stack }}
          stack-no-global: ${{ matrix.stack }}
      - uses: actions/checkout@v2
      - run: tools/testscript prepare
      - run: tools/testscript build
